version: 2

run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gocritic

  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
      
