version: 1

run:
  timeout: 3m
  modules-download-mode: readonly 

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gocritic

linters-settings:
  govet:
    enable-all: true