// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "PRmanager/internal/models"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreatePullRequestAndReview mocks base method.
func (m *MockRepositoryInterface) CreatePullRequestAndReview(ctx context.Context, pr *models.PullRequest, reviews []*models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequestAndReview", ctx, pr, reviews)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePullRequestAndReview indicates an expected call of CreatePullRequestAndReview.
func (mr *MockRepositoryInterfaceMockRecorder) CreatePullRequestAndReview(ctx, pr, reviews interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequestAndReview", reflect.TypeOf((*MockRepositoryInterface)(nil).CreatePullRequestAndReview), ctx, pr, reviews)
}

// CreateTeam mocks base method.
func (m *MockRepositoryInterface) CreateTeam(ctx context.Context, team *models.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockRepositoryInterfaceMockRecorder) CreateTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateTeam), ctx, team)
}

// DeleteReview mocks base method.
func (m *MockRepositoryInterface) DeleteReview(ctx context.Context, prId, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReview", ctx, prId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReview indicates an expected call of DeleteReview.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteReview(ctx, prId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReview", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteReview), ctx, prId, userId)
}

// GetListReviewsByUserId mocks base method.
func (m *MockRepositoryInterface) GetListReviewsByUserId(ctx context.Context, userId int) ([]*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListReviewsByUserId", ctx, userId)
	ret0, _ := ret[0].([]*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListReviewsByUserId indicates an expected call of GetListReviewsByUserId.
func (mr *MockRepositoryInterfaceMockRecorder) GetListReviewsByUserId(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListReviewsByUserId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetListReviewsByUserId), ctx, userId)
}

// GetPullRequestById mocks base method.
func (m *MockRepositoryInterface) GetPullRequestById(ctx context.Context, prSystemId string) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestById", ctx, prSystemId)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestById indicates an expected call of GetPullRequestById.
func (mr *MockRepositoryInterfaceMockRecorder) GetPullRequestById(ctx, prSystemId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetPullRequestById), ctx, prSystemId)
}

// GetTeamByName mocks base method.
func (m *MockRepositoryInterface) GetTeamByName(ctx context.Context, teamName string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, teamName)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockRepositoryInterfaceMockRecorder) GetTeamByName(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTeamByName), ctx, teamName)
}

// GetTeamMembers mocks base method.
func (m *MockRepositoryInterface) GetTeamMembers(ctx context.Context, teamId int) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamMembers", ctx, teamId)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamMembers indicates an expected call of GetTeamMembers.
func (mr *MockRepositoryInterfaceMockRecorder) GetTeamMembers(ctx, teamId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamMembers", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTeamMembers), ctx, teamId)
}

// GetUserBySystemId mocks base method.
func (m *MockRepositoryInterface) GetUserBySystemId(ctx context.Context, systemId string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBySystemId", ctx, systemId)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBySystemId indicates an expected call of GetUserBySystemId.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserBySystemId(ctx, systemId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBySystemId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserBySystemId), ctx, systemId)
}

// PullRequestExists mocks base method.
func (m *MockRepositoryInterface) PullRequestExists(ctx context.Context, prSystemID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestExists", ctx, prSystemID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestExists indicates an expected call of PullRequestExists.
func (mr *MockRepositoryInterfaceMockRecorder) PullRequestExists(ctx, prSystemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestExists", reflect.TypeOf((*MockRepositoryInterface)(nil).PullRequestExists), ctx, prSystemID)
}

// ReplaceReviewers mocks base method.
func (m *MockRepositoryInterface) ReplaceReviewers(ctx context.Context, prId, oldReviewerId, newReviewerId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceReviewers", ctx, prId, oldReviewerId, newReviewerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceReviewers indicates an expected call of ReplaceReviewers.
func (mr *MockRepositoryInterfaceMockRecorder) ReplaceReviewers(ctx, prId, oldReviewerId, newReviewerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceReviewers", reflect.TypeOf((*MockRepositoryInterface)(nil).ReplaceReviewers), ctx, prId, oldReviewerId, newReviewerId)
}

// SetIsActive mocks base method.
func (m *MockRepositoryInterface) SetIsActive(ctx context.Context, userID string, isActive bool) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockRepositoryInterfaceMockRecorder) SetIsActive(ctx, userID, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockRepositoryInterface)(nil).SetIsActive), ctx, userID, isActive)
}

// SetMergedStatusPullRequest mocks base method.
func (m *MockRepositoryInterface) SetMergedStatusPullRequest(ctx context.Context, prId int) (sql.NullTime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMergedStatusPullRequest", ctx, prId)
	ret0, _ := ret[0].(sql.NullTime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMergedStatusPullRequest indicates an expected call of SetMergedStatusPullRequest.
func (mr *MockRepositoryInterfaceMockRecorder) SetMergedStatusPullRequest(ctx, prId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMergedStatusPullRequest", reflect.TypeOf((*MockRepositoryInterface)(nil).SetMergedStatusPullRequest), ctx, prId)
}

// TeamExists mocks base method.
func (m *MockRepositoryInterface) TeamExists(ctx context.Context, teamName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeamExists", ctx, teamName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TeamExists indicates an expected call of TeamExists.
func (mr *MockRepositoryInterfaceMockRecorder) TeamExists(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeamExists", reflect.TypeOf((*MockRepositoryInterface)(nil).TeamExists), ctx, teamName)
}
